spring:
  application:
    name: FintechApp
  datasource:
    url:
    username:
    password:

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
server:
  servlet:
    port: 8080
    contextPath: /fintech

secretKey: fintech
