spring:
  application:
    name: FintechApp
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
server:
  servlet:
    port: 8080
    contextPath: /fintech

jwt:
  secret:

logging:
  level:
    org:
      springframework:
        security: DEBUG